config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#ominauth'

  resources :reviews
  resources :coffees do 
    resources :reviews, only: [:new, :index]
  end 
  resources :brands
  resources :users
  get 'coffee/index'
  get 'coffee/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :coffees
end

app/models/coffee.rb
class Coffee < ApplicationRecord
    belongs_to :brand
    belongs_to :user #creator of it 
    has_many :reviews 
    has_many :users, through: :reviews #people who have reviewed it

    validates :flavor, presence: true 
    validate :not_a_duplicate 

    scope :order_by_rating, -> {joins(:reviews).group(:id).order('avg(stars) desc')}

    def self.alpha
        order(:flavor)
    end 


    def brand_attributes=(attributes)
        brand = Brand.find_or_create_by(attributes) if 
        !attributes['name'].empty?
    end 



    def not_a_duplicate 
        if Coffee.find_by(flavor: flavor, brand_id: brand_id)
            errors.add(:flavor, "has already been added for that brand, try again!")
        end 
    end 

    def flavor_and_brand
        "#{flavor} - #{brand.name}"
    end 
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user 
    belongs_to :coffee 

    validates :title, presence: true 
    validates :stars, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 6}

    validates :coffee_id, uniqueness: { scope: :user, message: "has already been reviewed by you" }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews 
    has_many :reviewed_coffees, through: :reviews, source: :coffee 

    has_many :coffees #that they have created 

    validates :username, uniqueness: true, presence: true 

    has_secure_password 

    def self.create_by_google_omniauth(auth)
          self.find_or_create_by(username: auth[:info][:email]) do |u| 
            u.password = SecureRandom.hex

        end 
    end 


    def self.create_by_github_omniauth(auth)
          self.find_or_create_by(username: auth[:info][:email]) do |u| 
            u.password = SecureRandom.hex
        end 
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private 

    def current_user 
        @current_user ||= User.find_by_id(session)[:user_id]
    end 
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController

    def new 
        @coffee = Coffee.new 
        @coffee.build_brand 
    end 

    def create 
        @coffee = Coffee.new(coffee_params)
        @coffee.user_id = session[:user_id]
        if @coffee.save #This is where validations happen
            redirect_to coffee_path(@coffee)
        else
            render :new 
        end 
    end 

    def index 
        @coffees = Coffee.order_by_rating.includes(:brand)
    end 

    def show
        @coffee = Coffee.find_by_id(params[:id])
    end 


    private 

    def coffee_params 
        params.require(coffee).permit(:flavor, :description, :brand_id, brand_attributes: [:name])
    end 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new 
      if @coffee =  Coffee.find_by_id(params[:coffee_id])
       @review = @coffee.reviews.build 
      else 
        @review = Review.new 
      end 
    end 

    def create 
        @review = Review.create(review_params)
        if @review.save #checks if its valid 
            redirect_to review_path(@review)
        else 
            render :new 
        end 
    end 

    def show
       @review = Review.find_by_id(params[:id])
    end 

    def index 

        if params[:coffee_id]
            @coffee =  Coffee.find_by_id(params[:coffee_id])
            @reviews = @coffee.reviews 
        else

        @reviews = Review.all 
    end 
end 

   
    private 

    def review_params
        params.require(:review).permit(:coffee_id, :content, :stars, :title)
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

    def welcome 

    end 

    def destroy 
        session.delete(:user_id)
        redirect_to '/'
    end 

    def new

    end 

    def create

        if params[:provider] == 'google_oauth2'
            @user = User.create_by_google_omniauth(auth)
            session[:user_id] = @user.id 
            redirect_to user_path(@user)

        elsif params[:provider] = 'github'
            @user = User.create_by_github_omniauth(auth)
            session[:user_id] = @user.id 
            redirect_to user_path(@user)

        else 

        @user = User.find_by(username: params[:user][:username])

        # if @user && @user.authenticate(params[:users][:password])

        if @user.try(:authenticate, params[:user][:password])
            session[:user_id] = @user_id 
            redirect_to user_path(@user)
        else 
            flash[:error] = 'Sorry, please try again!'
            redirect_to login_path
        end 
    end 

    def omniauth 
       @user = User.create_by_google_omniauth(auth)


            session[:user_id] = @user.id 
            redirect_to_user_path(@user)

    end 

    private 

    def auth 
        request.env['omniauth.auth']
    end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new
    end 


    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else
            render :new 
        end 
    end 

    def show 
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user 
    end 

    private 

    def user_params 
        params.require(:user).permit(:username, :password)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/coffee_helper.rb
module CoffeeHelper
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

    def display_header(review)
        if params[:coffee_id]
            content_tag(:h1, "Add a Review for #{review.coffee.flavor} - #{review.coffee.brand.name}")
        else 
            content_tag(:h1, "Create a review")
        end 
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/index.html.erb
<h1>All the Brands!</h1>

<ol>
    <% @brands.each do |b|%>
        <li><%= b.name%></li>
        <% end %>
</ol>

app/views/coffee/index.html.erb
<h1>Coffee#index</h1>
<p>Find me in app/views/coffee/index.html.erb</p>

app/views/coffee/show.html.erb
<h1>Coffee#show</h1>
<p>Find me in app/views/coffee/show.html.erb</p>

app/views/coffees/index.html.erb
<h1>All of the Coffees</h1>

<% @coffees.each do  |c| %>

    <h2><%= c.flavor%> - <%= c.brand.name %> </h2>
    <%= link_to "Write a Review", new_coffee_review_path(c.id)%>
  <div>
    <p><%= c.description %></p>
  </div>
<% end %>

app/views/coffees/new.html.erb
<h1>Make a new coffee!</h1>

<%= render partial: 'layouts/errors', locals: {object: @coffee} %>


<%= form_for(@coffee) do |f|%>
    <div>
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
    </div>

    <div>
    <%= f.label :description %>
    <%= f.text_field :description %> 
    </div>

    <p> Select a Brand that already exist: </p>
    <div>
        <%= f.collection_select :brand_id, Brand.all, :id, :name %>
    </div>


    <p>Or create a new Brand: </p>
    <div>
        <%= f.fields_for :brand do |b| %>
        <%= b.label :name %>
        <%= b.text_field :name %>
        <% end %>
    </div>
    <br>
        <%= f.submit  %>
    <% end %>

app/views/coffees/show.html.erb
<h1><%= @coffee.flavor%> </h1>

<% if @coffee.image.attached? %>
    <%= image_tag url_for(@coffee.image) %>
    <% end %>

<h2> <%= @coffee.brand_name%> </h2>
<div>
    <p> <%= @coffee.description %></p>
</div>

<h3>Added by: <%= link_to @coffee.user, user_path(@user)%></h3>

<%= link_to "Edit #{@coffee.flavor}", edit_coffee_path(@coffee) if @coffee.user == current_user%>

<br></br>

<%= link_to "See all Reviews", coffee_reviews_path(@coffee) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CupOfJoe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
      <%= link_to "Log Out", logout_path, method: :delete %>
      <%= link_to "Add a Coffee", new_coffee_path %>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<h1>All the Reviews</h1>

<ul>
<% @reviews.each do |r| %>
    <li><%= r.coffee.flavor%> - <%= r.stars%></li><br>
<% end %>
</ul>

app/views/reviews/new.html.erb
<%= display_header(@review)%>

<%= render partial: 'layouts/errors', locals: {object: @review} %>



<%= form_for(@review) do |f| %>
  <% if params[:coffee_id] %>
    <%= f.hidden_field :coffee_id %>
      <% else %>
    <div>
      <%= f.label :coffee_id, "Select a Coffee" %>
      <%= f.collection_select :coffee_id, Coffee.alpha, :id, :flavor_and_brand, include_blank: true %>
      </div>
      <% end %>
      <div>
        <%= f.label :stars %>
        <%= f.number_field :stars, min:0, max:5 %>
    </div>
    <br>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %> 
    </div>
    <br>
    <div>
        <%= f.label :content %>
        <%= f.text_area :content, size: "25x10" %>
    </div>
    <br>



    <%= f.submit %>

    <% end %>

app/views/reviews/show.html.erb
<h1><%= @review.title %> - <<%= @review.stars %></h1>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<%= form_for(@user) do |f|%>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %> 

    <%= f.submit "Sign Up" %>

    <% end %>

app/views/users/show.html.erb
Welcome <%= @user.username %>! 